version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - downloads:/downloads
    depends_on:
      - api
      - extractor

  api:
    build:
      context: ./api
    restart: unless-stopped
    ports:
      - "3005:3005"
    
  extractor:
    build:
      context: ./extractor
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - downloads:/app/downloads

volumes:
  caddy_data:
  caddy_config:
  downloads:
